//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace TTRider.ExportExtensions.Service_References.ExtensionService {
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="IdeCategory", Namespace="http://schemas.datacontract.org/2004/07/Galleries.Domain.Model")]
    [Serializable()]
    public partial class IdeCategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [NonSerialized()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private System.Collections.Generic.List<IdeCategory> ChildrenField;
        
        [OptionalField()]
        private bool HasMoreField;
        
        [OptionalField()]
        private System.Guid IdField;
        
        [OptionalField()]
        private IdeCategory ParentField;
        
        [OptionalField()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public System.Collections.Generic.List<IdeCategory> Children {
            get {
                return this.ChildrenField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildrenField, value) != true)) {
                    this.ChildrenField = value;
                    this.RaisePropertyChanged("Children");
                }
            }
        }
        
        [DataMember()]
        public bool HasMore {
            get {
                return this.HasMoreField;
            }
            set {
                if ((this.HasMoreField.Equals(value) != true)) {
                    this.HasMoreField = value;
                    this.RaisePropertyChanged("HasMore");
                }
            }
        }
        
        [DataMember()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [DataMember()]
        public IdeCategory Parent {
            get {
                return this.ParentField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentField, value) != true)) {
                    this.ParentField = value;
                    this.RaisePropertyChanged("Parent");
                }
            }
        }
        
        [DataMember()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="ReleaseQueryResult", Namespace="http://schemas.datacontract.org/2004/07/VsGallery.WebServices")]
    [Serializable()]
    public partial class ReleaseQueryResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [NonSerialized()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private System.Collections.Generic.List<Release> ReleasesField;
        
        [OptionalField()]
        private int TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public System.Collections.Generic.List<Release> Releases {
            get {
                return this.ReleasesField;
            }
            set {
                if ((object.ReferenceEquals(this.ReleasesField, value) != true)) {
                    this.ReleasesField = value;
                    this.RaisePropertyChanged("Releases");
                }
            }
        }
        
        [DataMember()]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="Release", Namespace="http://schemas.datacontract.org/2004/07/Galleries.Domain.Model")]
    [Serializable()]
    public partial class Release : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [NonSerialized()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private System.Nullable<System.DateTime> DateReleasedField;
        
        [OptionalField()]
        private string DescriptionField;
        
        [OptionalField()]
        private System.Collections.Generic.List<ReleaseFile> FilesField;
        
        [OptionalField()]
        private int IdField;
        
        [OptionalField()]
        private bool IsCurrentReleaseField;
        
        [OptionalField()]
        private bool IsDisplayedOnHomePageField;
        
        [OptionalField()]
        private bool IsPublicField;
        
        [OptionalField()]
        private string NameField;
        
        [OptionalField()]
        private Project ProjectField;
        
        [OptionalField()]
        private double RatingField;
        
        [OptionalField()]
        private int RatingsCountField;
        
        [OptionalField()]
        private int ReviewsCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public System.Nullable<System.DateTime> DateReleased {
            get {
                return this.DateReleasedField;
            }
            set {
                if ((this.DateReleasedField.Equals(value) != true)) {
                    this.DateReleasedField = value;
                    this.RaisePropertyChanged("DateReleased");
                }
            }
        }
        
        [DataMember()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [DataMember()]
        public System.Collections.Generic.List<ReleaseFile> Files {
            get {
                return this.FilesField;
            }
            set {
                if ((object.ReferenceEquals(this.FilesField, value) != true)) {
                    this.FilesField = value;
                    this.RaisePropertyChanged("Files");
                }
            }
        }
        
        [DataMember()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [DataMember()]
        public bool IsCurrentRelease {
            get {
                return this.IsCurrentReleaseField;
            }
            set {
                if ((this.IsCurrentReleaseField.Equals(value) != true)) {
                    this.IsCurrentReleaseField = value;
                    this.RaisePropertyChanged("IsCurrentRelease");
                }
            }
        }
        
        [DataMember()]
        public bool IsDisplayedOnHomePage {
            get {
                return this.IsDisplayedOnHomePageField;
            }
            set {
                if ((this.IsDisplayedOnHomePageField.Equals(value) != true)) {
                    this.IsDisplayedOnHomePageField = value;
                    this.RaisePropertyChanged("IsDisplayedOnHomePage");
                }
            }
        }
        
        [DataMember()]
        public bool IsPublic {
            get {
                return this.IsPublicField;
            }
            set {
                if ((this.IsPublicField.Equals(value) != true)) {
                    this.IsPublicField = value;
                    this.RaisePropertyChanged("IsPublic");
                }
            }
        }
        
        [DataMember()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [DataMember()]
        public Project Project {
            get {
                return this.ProjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectField, value) != true)) {
                    this.ProjectField = value;
                    this.RaisePropertyChanged("Project");
                }
            }
        }
        
        [DataMember()]
        public double Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [DataMember()]
        public int RatingsCount {
            get {
                return this.RatingsCountField;
            }
            set {
                if ((this.RatingsCountField.Equals(value) != true)) {
                    this.RatingsCountField = value;
                    this.RaisePropertyChanged("RatingsCount");
                }
            }
        }
        
        [DataMember()]
        public int ReviewsCount {
            get {
                return this.ReviewsCountField;
            }
            set {
                if ((this.ReviewsCountField.Equals(value) != true)) {
                    this.ReviewsCountField = value;
                    this.RaisePropertyChanged("ReviewsCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="Project", Namespace="http://schemas.datacontract.org/2004/07/Galleries.Domain.Model")]
    [Serializable()]
    public partial class Project : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [NonSerialized()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private int AffiliateIdField;
        
        [OptionalField()]
        private System.Collections.Generic.List<Category> CategoriesField;
        
        [OptionalField()]
        private System.DateTime CreatedDateField;
        
        [OptionalField()]
        private Release CurrentReleaseField;
        
        [OptionalField()]
        private string DescriptionField;
        
        [OptionalField()]
        private bool DiscussionsEnabledField;
        
        [OptionalField()]
        private bool FileReleaseEnabledField;
        
        [OptionalField()]
        private int IdField;
        
        [OptionalField()]
        private string InitialProjectNameField;
        
        [OptionalField()]
        private bool IsPublishedField;
        
        [OptionalField()]
        private System.Collections.Generic.Dictionary<string, string> MetadataField;
        
        [OptionalField()]
        private System.DateTime ModifiedDateField;
        
        [OptionalField()]
        private string NameField;
        
        [OptionalField()]
        private System.Collections.Generic.List<Release> ReleasesField;
        
        [OptionalField()]
        private bool SourceCodeBrowsingEnabledField;
        
        [OptionalField()]
        private System.Collections.Generic.List<string> TagsField;
        
        [OptionalField()]
        private string TitleField;
        
        [OptionalField()]
        private bool WorkItemTrackingEnabledField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public int AffiliateId {
            get {
                return this.AffiliateIdField;
            }
            set {
                if ((this.AffiliateIdField.Equals(value) != true)) {
                    this.AffiliateIdField = value;
                    this.RaisePropertyChanged("AffiliateId");
                }
            }
        }
        
        [DataMember()]
        public System.Collections.Generic.List<Category> Categories {
            get {
                return this.CategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriesField, value) != true)) {
                    this.CategoriesField = value;
                    this.RaisePropertyChanged("Categories");
                }
            }
        }
        
        [DataMember()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [DataMember()]
        public Release CurrentRelease {
            get {
                return this.CurrentReleaseField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentReleaseField, value) != true)) {
                    this.CurrentReleaseField = value;
                    this.RaisePropertyChanged("CurrentRelease");
                }
            }
        }
        
        [DataMember()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [DataMember()]
        public bool DiscussionsEnabled {
            get {
                return this.DiscussionsEnabledField;
            }
            set {
                if ((this.DiscussionsEnabledField.Equals(value) != true)) {
                    this.DiscussionsEnabledField = value;
                    this.RaisePropertyChanged("DiscussionsEnabled");
                }
            }
        }
        
        [DataMember()]
        public bool FileReleaseEnabled {
            get {
                return this.FileReleaseEnabledField;
            }
            set {
                if ((this.FileReleaseEnabledField.Equals(value) != true)) {
                    this.FileReleaseEnabledField = value;
                    this.RaisePropertyChanged("FileReleaseEnabled");
                }
            }
        }
        
        [DataMember()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [DataMember()]
        public string InitialProjectName {
            get {
                return this.InitialProjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.InitialProjectNameField, value) != true)) {
                    this.InitialProjectNameField = value;
                    this.RaisePropertyChanged("InitialProjectName");
                }
            }
        }
        
        [DataMember()]
        public bool IsPublished {
            get {
                return this.IsPublishedField;
            }
            set {
                if ((this.IsPublishedField.Equals(value) != true)) {
                    this.IsPublishedField = value;
                    this.RaisePropertyChanged("IsPublished");
                }
            }
        }
        
        [DataMember()]
        public System.Collections.Generic.Dictionary<string, string> Metadata {
            get {
                return this.MetadataField;
            }
            set {
                if ((object.ReferenceEquals(this.MetadataField, value) != true)) {
                    this.MetadataField = value;
                    this.RaisePropertyChanged("Metadata");
                }
            }
        }
        
        [DataMember()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [DataMember()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [DataMember()]
        public System.Collections.Generic.List<Release> Releases {
            get {
                return this.ReleasesField;
            }
            set {
                if ((object.ReferenceEquals(this.ReleasesField, value) != true)) {
                    this.ReleasesField = value;
                    this.RaisePropertyChanged("Releases");
                }
            }
        }
        
        [DataMember()]
        public bool SourceCodeBrowsingEnabled {
            get {
                return this.SourceCodeBrowsingEnabledField;
            }
            set {
                if ((this.SourceCodeBrowsingEnabledField.Equals(value) != true)) {
                    this.SourceCodeBrowsingEnabledField = value;
                    this.RaisePropertyChanged("SourceCodeBrowsingEnabled");
                }
            }
        }
        
        [DataMember()]
        public System.Collections.Generic.List<string> Tags {
            get {
                return this.TagsField;
            }
            set {
                if ((object.ReferenceEquals(this.TagsField, value) != true)) {
                    this.TagsField = value;
                    this.RaisePropertyChanged("Tags");
                }
            }
        }
        
        [DataMember()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [DataMember()]
        public bool WorkItemTrackingEnabled {
            get {
                return this.WorkItemTrackingEnabledField;
            }
            set {
                if ((this.WorkItemTrackingEnabledField.Equals(value) != true)) {
                    this.WorkItemTrackingEnabledField = value;
                    this.RaisePropertyChanged("WorkItemTrackingEnabled");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="ReleaseFile", Namespace="http://schemas.datacontract.org/2004/07/Galleries.Domain.Model")]
    [Serializable()]
    public partial class ReleaseFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [NonSerialized()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private FileAttachment AttachmentField;
        
        [OptionalField()]
        private string DescriptionField;
        
        [OptionalField()]
        private int DownloadCountField;
        
        [OptionalField()]
        private int IdField;
        
        [OptionalField()]
        private System.Collections.Generic.Dictionary<string, string> MetadataField;
        
        [OptionalField()]
        private Release ParentField;
        
        [OptionalField()]
        private ReleaseFileType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public FileAttachment Attachment {
            get {
                return this.AttachmentField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentField, value) != true)) {
                    this.AttachmentField = value;
                    this.RaisePropertyChanged("Attachment");
                }
            }
        }
        
        [DataMember()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [DataMember()]
        public int DownloadCount {
            get {
                return this.DownloadCountField;
            }
            set {
                if ((this.DownloadCountField.Equals(value) != true)) {
                    this.DownloadCountField = value;
                    this.RaisePropertyChanged("DownloadCount");
                }
            }
        }
        
        [DataMember()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [DataMember()]
        public System.Collections.Generic.Dictionary<string, string> Metadata {
            get {
                return this.MetadataField;
            }
            set {
                if ((object.ReferenceEquals(this.MetadataField, value) != true)) {
                    this.MetadataField = value;
                    this.RaisePropertyChanged("Metadata");
                }
            }
        }
        
        [DataMember()]
        public Release Parent {
            get {
                return this.ParentField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentField, value) != true)) {
                    this.ParentField = value;
                    this.RaisePropertyChanged("Parent");
                }
            }
        }
        
        [DataMember()]
        public ReleaseFileType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="FileAttachment", Namespace="http://schemas.datacontract.org/2004/07/Galleries.Domain.Model")]
    [Serializable()]
    public partial class FileAttachment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [NonSerialized()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private string FileNameField;
        
        [OptionalField()]
        private int IdField;
        
        [OptionalField()]
        private System.DateTime UploadDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [DataMember()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [DataMember()]
        public System.DateTime UploadDate {
            get {
                return this.UploadDateField;
            }
            set {
                if ((this.UploadDateField.Equals(value) != true)) {
                    this.UploadDateField = value;
                    this.RaisePropertyChanged("UploadDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="ReleaseFileType", Namespace="http://schemas.datacontract.org/2004/07/Galleries.Domain.Model")]
    [Serializable()]
    public partial class ReleaseFileType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [NonSerialized()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private string DescriptionField;
        
        [OptionalField()]
        private string IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [DataMember()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/Galleries.Domain.Model")]
    [Serializable()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [NonSerialized()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private System.Collections.Generic.List<Category> ChildrenField;
        
        [OptionalField()]
        private int IdField;
        
        [OptionalField()]
        private Category ParentField;
        
        [OptionalField()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public System.Collections.Generic.List<Category> Children {
            get {
                return this.ChildrenField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildrenField, value) != true)) {
                    this.ChildrenField = value;
                    this.RaisePropertyChanged("Children");
                }
            }
        }
        
        [DataMember()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [DataMember()]
        public Category Parent {
            get {
                return this.ParentField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentField, value) != true)) {
                    this.ParentField = value;
                    this.RaisePropertyChanged("Parent");
                }
            }
        }
        
        [DataMember()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExtensionService.IVsIdeService")]
    public interface IVsIdeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVsIdeService/GetCategoryTree", ReplyAction="http://tempuri.org/IVsIdeService/GetCategoryTreeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Guid), Action="http://galleries.msdn.microsoft.com/faults/generic", Name="guid", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        IdeCategory GetCategoryTree(System.Guid categoryId, int level, string projectType, string templateType, System.Collections.Generic.List<string> skus, System.Collections.Generic.List<string> subSkus, System.Collections.Generic.List<int> templateGroupIds, System.Collections.Generic.List<int> vsVersions, string cultureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVsIdeService/GetCategoryTree", ReplyAction="http://tempuri.org/IVsIdeService/GetCategoryTreeResponse")]
        System.Threading.Tasks.Task<IdeCategory> GetCategoryTreeAsync(System.Guid categoryId, int level, string projectType, string templateType, System.Collections.Generic.List<string> skus, System.Collections.Generic.List<string> subSkus, System.Collections.Generic.List<int> templateGroupIds, System.Collections.Generic.List<int> vsVersions, string cultureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVsIdeService/GetRootCategories", ReplyAction="http://tempuri.org/IVsIdeService/GetRootCategoriesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Guid), Action="http://galleries.msdn.microsoft.com/faults/generic", Name="guid", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Collections.Generic.List<IdeCategory> GetRootCategories(string cultureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVsIdeService/GetRootCategories", ReplyAction="http://tempuri.org/IVsIdeService/GetRootCategoriesResponse")]
        System.Threading.Tasks.Task<List<IdeCategory>> GetRootCategoriesAsync(string cultureName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVsIdeService/SearchReleases", ReplyAction="http://tempuri.org/IVsIdeService/SearchReleasesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Guid), Action="http://galleries.msdn.microsoft.com/faults/generic", Name="guid", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        ReleaseQueryResult SearchReleases(string searchText, string whereClause, string orderByClause, System.Nullable<int> locale, System.Nullable<int> skip, System.Nullable<int> take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVsIdeService/SearchReleases", ReplyAction="http://tempuri.org/IVsIdeService/SearchReleasesResponse")]
        System.Threading.Tasks.Task<ReleaseQueryResult> SearchReleasesAsync(string searchText, string whereClause, string orderByClause, System.Nullable<int> locale, System.Nullable<int> skip, System.Nullable<int> take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVsIdeService/GetRootCategories2", ReplyAction="http://tempuri.org/IVsIdeService/GetRootCategories2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Guid), Action="http://galleries.msdn.microsoft.com/faults/generic", Name="guid", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Collections.Generic.List<IdeCategory> GetRootCategories2(System.Collections.Generic.Dictionary<string, string> requestContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVsIdeService/GetRootCategories2", ReplyAction="http://tempuri.org/IVsIdeService/GetRootCategories2Response")]
        System.Threading.Tasks.Task<List<IdeCategory>> GetRootCategories2Async(System.Collections.Generic.Dictionary<string, string> requestContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVsIdeService/GetCategoryTree2", ReplyAction="http://tempuri.org/IVsIdeService/GetCategoryTree2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Guid), Action="http://galleries.msdn.microsoft.com/faults/generic", Name="guid", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        IdeCategory GetCategoryTree2(System.Guid categoryId, int level, System.Collections.Generic.Dictionary<string, string> requestContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVsIdeService/GetCategoryTree2", ReplyAction="http://tempuri.org/IVsIdeService/GetCategoryTree2Response")]
        System.Threading.Tasks.Task<IdeCategory> GetCategoryTree2Async(System.Guid categoryId, int level, System.Collections.Generic.Dictionary<string, string> requestContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVsIdeService/SearchReleases2", ReplyAction="http://tempuri.org/IVsIdeService/SearchReleases2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Guid), Action="http://galleries.msdn.microsoft.com/faults/generic", Name="guid", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        ReleaseQueryResult SearchReleases2(string searchText, string whereClause, string orderByClause, System.Nullable<int> skip, System.Nullable<int> take, System.Collections.Generic.Dictionary<string, string> requestContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVsIdeService/SearchReleases2", ReplyAction="http://tempuri.org/IVsIdeService/SearchReleases2Response")]
        System.Threading.Tasks.Task<ReleaseQueryResult> SearchReleases2Async(string searchText, string whereClause, string orderByClause, System.Nullable<int> skip, System.Nullable<int> take, System.Collections.Generic.Dictionary<string, string> requestContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVsIdeService/GetCurrentVersionsForVsixList", ReplyAction="http://tempuri.org/IVsIdeService/GetCurrentVersionsForVsixListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Guid), Action="http://galleries.msdn.microsoft.com/faults/generic", Name="guid", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        System.Collections.Generic.List<string> GetCurrentVersionsForVsixList(System.Collections.Generic.List<string> vsixIds, System.Collections.Generic.Dictionary<string, string> requestContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVsIdeService/GetCurrentVersionsForVsixList", ReplyAction="http://tempuri.org/IVsIdeService/GetCurrentVersionsForVsixListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetCurrentVersionsForVsixListAsync(System.Collections.Generic.List<string> vsixIds, System.Collections.Generic.Dictionary<string, string> requestContext);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVsIdeServiceChannel : IVsIdeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VsIdeServiceClient : System.ServiceModel.ClientBase<IVsIdeService>, IVsIdeService {
        
        public VsIdeServiceClient() {
        }
        
        public VsIdeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VsIdeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VsIdeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VsIdeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IdeCategory GetCategoryTree(System.Guid categoryId, int level, string projectType, string templateType, System.Collections.Generic.List<string> skus, System.Collections.Generic.List<string> subSkus, System.Collections.Generic.List<int> templateGroupIds, System.Collections.Generic.List<int> vsVersions, string cultureName) {
            return base.Channel.GetCategoryTree(categoryId, level, projectType, templateType, skus, subSkus, templateGroupIds, vsVersions, cultureName);
        }
        
        public System.Threading.Tasks.Task<IdeCategory> GetCategoryTreeAsync(System.Guid categoryId, int level, string projectType, string templateType, System.Collections.Generic.List<string> skus, System.Collections.Generic.List<string> subSkus, System.Collections.Generic.List<int> templateGroupIds, System.Collections.Generic.List<int> vsVersions, string cultureName) {
            return base.Channel.GetCategoryTreeAsync(categoryId, level, projectType, templateType, skus, subSkus, templateGroupIds, vsVersions, cultureName);
        }
        
        public System.Collections.Generic.List<IdeCategory> GetRootCategories(string cultureName) {
            return base.Channel.GetRootCategories(cultureName);
        }
        
        public System.Threading.Tasks.Task<List<IdeCategory>> GetRootCategoriesAsync(string cultureName) {
            return base.Channel.GetRootCategoriesAsync(cultureName);
        }
        
        public ReleaseQueryResult SearchReleases(string searchText, string whereClause, string orderByClause, System.Nullable<int> locale, System.Nullable<int> skip, System.Nullable<int> take) {
            return base.Channel.SearchReleases(searchText, whereClause, orderByClause, locale, skip, take);
        }
        
        public System.Threading.Tasks.Task<ReleaseQueryResult> SearchReleasesAsync(string searchText, string whereClause, string orderByClause, System.Nullable<int> locale, System.Nullable<int> skip, System.Nullable<int> take) {
            return base.Channel.SearchReleasesAsync(searchText, whereClause, orderByClause, locale, skip, take);
        }
        
        public System.Collections.Generic.List<IdeCategory> GetRootCategories2(System.Collections.Generic.Dictionary<string, string> requestContext) {
            return base.Channel.GetRootCategories2(requestContext);
        }
        
        public System.Threading.Tasks.Task<List<IdeCategory>> GetRootCategories2Async(System.Collections.Generic.Dictionary<string, string> requestContext) {
            return base.Channel.GetRootCategories2Async(requestContext);
        }
        
        public IdeCategory GetCategoryTree2(System.Guid categoryId, int level, System.Collections.Generic.Dictionary<string, string> requestContext) {
            return base.Channel.GetCategoryTree2(categoryId, level, requestContext);
        }
        
        public System.Threading.Tasks.Task<IdeCategory> GetCategoryTree2Async(System.Guid categoryId, int level, System.Collections.Generic.Dictionary<string, string> requestContext) {
            return base.Channel.GetCategoryTree2Async(categoryId, level, requestContext);
        }
        
        public ReleaseQueryResult SearchReleases2(string searchText, string whereClause, string orderByClause, System.Nullable<int> skip, System.Nullable<int> take, System.Collections.Generic.Dictionary<string, string> requestContext) {
            return base.Channel.SearchReleases2(searchText, whereClause, orderByClause, skip, take, requestContext);
        }
        
        public System.Threading.Tasks.Task<ReleaseQueryResult> SearchReleases2Async(string searchText, string whereClause, string orderByClause, System.Nullable<int> skip, System.Nullable<int> take, System.Collections.Generic.Dictionary<string, string> requestContext) {
            return base.Channel.SearchReleases2Async(searchText, whereClause, orderByClause, skip, take, requestContext);
        }
        
        public System.Collections.Generic.List<string> GetCurrentVersionsForVsixList(System.Collections.Generic.List<string> vsixIds, System.Collections.Generic.Dictionary<string, string> requestContext) {
            return base.Channel.GetCurrentVersionsForVsixList(vsixIds, requestContext);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetCurrentVersionsForVsixListAsync(System.Collections.Generic.List<string> vsixIds, System.Collections.Generic.Dictionary<string, string> requestContext) {
            return base.Channel.GetCurrentVersionsForVsixListAsync(vsixIds, requestContext);
        }
    }
}
